model:
  model_variant: 3d
  model_size: small
  lora: true

pretrained:
  checkpoint: /mnt/c/Users/puruv/Projects/fomo26/checkpoints/small/neco/encoder_teacher.ckpt

data:
  dataset_name: CLS002_FOMO26_Infarct
  crop_size: [378, 378, 32]
  batch_size: 1
  num_workers: 1

optim:
  opt: SGD

trainer:
  max_steps: 100
  precision: 32-true
  devices: auto
  strategy: auto
  gradient_clip_val: 3.0
